language: go
sudo: required

go:
  - 1.10.x

before_install:
  - go get -u github.com/haya14busa/goverage

script:
  - go test $(go list ./... | grep -v 'ttt') -bench .
  - ./cover.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
