language: go
sudo: required

go:
  - 1.11.x

env:
  - GO111MODULE=on

install: true

before_install:
  - go get -u github.com/haya14busa/goverage

script:
  - ./cmd/cover.sh

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
